"""password hash to pass secure Migration

Revision ID: 036a477cbaaf
Revises: c65acf85fdab
Create Date: 2020-06-05 04:17:47.622572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036a477cbaaf'
down_revision = 'c65acf85fdab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###
